#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LabsControl1")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertStatus_Agendamento(Status_Agendamento instance);
  partial void UpdateStatus_Agendamento(Status_Agendamento instance);
  partial void DeleteStatus_Agendamento(Status_Agendamento instance);
  partial void Inserttb_Agendamento(tb_Agendamento instance);
  partial void Updatetb_Agendamento(tb_Agendamento instance);
  partial void Deletetb_Agendamento(tb_Agendamento instance);
  partial void Inserttb_ComputadorSoftware(tb_ComputadorSoftware instance);
  partial void Updatetb_ComputadorSoftware(tb_ComputadorSoftware instance);
  partial void Deletetb_ComputadorSoftware(tb_ComputadorSoftware instance);
  partial void Inserttb_Horario(tb_Horario instance);
  partial void Updatetb_Horario(tb_Horario instance);
  partial void Deletetb_Horario(tb_Horario instance);
  partial void Inserttb_Laboratorio(tb_Laboratorio instance);
  partial void Updatetb_Laboratorio(tb_Laboratorio instance);
  partial void Deletetb_Laboratorio(tb_Laboratorio instance);
  partial void Inserttb_Ocorrencia(tb_Ocorrencia instance);
  partial void Updatetb_Ocorrencia(tb_Ocorrencia instance);
  partial void Deletetb_Ocorrencia(tb_Ocorrencia instance);
  partial void Inserttb_Software(tb_Software instance);
  partial void Updatetb_Software(tb_Software instance);
  partial void Deletetb_Software(tb_Software instance);
  partial void Inserttb_Usuario(tb_Usuario instance);
  partial void Updatetb_Usuario(tb_Usuario instance);
  partial void Deletetb_Usuario(tb_Usuario instance);
  partial void Inserttb_Computador(tb_Computador instance);
  partial void Updatetb_Computador(tb_Computador instance);
  partial void Deletetb_Computador(tb_Computador instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LabsControl1ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Status_Agendamento> Status_Agendamentos
	{
		get
		{
			return this.GetTable<Status_Agendamento>();
		}
	}
	
	public System.Data.Linq.Table<tb_Agendamento> tb_Agendamentos
	{
		get
		{
			return this.GetTable<tb_Agendamento>();
		}
	}
	
	public System.Data.Linq.Table<tb_ComputadorSoftware> tb_ComputadorSoftwares
	{
		get
		{
			return this.GetTable<tb_ComputadorSoftware>();
		}
	}
	
	public System.Data.Linq.Table<tb_Horario> tb_Horarios
	{
		get
		{
			return this.GetTable<tb_Horario>();
		}
	}
	
	public System.Data.Linq.Table<tb_Laboratorio> tb_Laboratorios
	{
		get
		{
			return this.GetTable<tb_Laboratorio>();
		}
	}
	
	public System.Data.Linq.Table<tb_Ocorrencia> tb_Ocorrencias
	{
		get
		{
			return this.GetTable<tb_Ocorrencia>();
		}
	}
	
	public System.Data.Linq.Table<tb_Software> tb_Softwares
	{
		get
		{
			return this.GetTable<tb_Software>();
		}
	}
	
	public System.Data.Linq.Table<tb_Usuario> tb_Usuarios
	{
		get
		{
			return this.GetTable<tb_Usuario>();
		}
	}
	
	public System.Data.Linq.Table<tb_Computador> tb_Computadors
	{
		get
		{
			return this.GetTable<tb_Computador>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status_Agendamento")]
public partial class Status_Agendamento : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Status_Agendamento;
	
	private string _NomeStatus;
	
	private EntitySet<tb_Agendamento> _tb_Agendamentos;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_Status_AgendamentoChanging(int value);
    partial void Onid_Status_AgendamentoChanged();
    partial void OnNomeStatusChanging(string value);
    partial void OnNomeStatusChanged();
    #endregion
	
	public Status_Agendamento()
	{
		this._tb_Agendamentos = new EntitySet<tb_Agendamento>(new Action<tb_Agendamento>(this.attach_tb_Agendamentos), new Action<tb_Agendamento>(this.detach_tb_Agendamentos));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Status_Agendamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Status_Agendamento
	{
		get
		{
			return this._id_Status_Agendamento;
		}
		set
		{
			if ((this._id_Status_Agendamento != value))
			{
				this.Onid_Status_AgendamentoChanging(value);
				this.SendPropertyChanging();
				this._id_Status_Agendamento = value;
				this.SendPropertyChanged("id_Status_Agendamento");
				this.Onid_Status_AgendamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeStatus", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string NomeStatus
	{
		get
		{
			return this._NomeStatus;
		}
		set
		{
			if ((this._NomeStatus != value))
			{
				this.OnNomeStatusChanging(value);
				this.SendPropertyChanging();
				this._NomeStatus = value;
				this.SendPropertyChanged("NomeStatus");
				this.OnNomeStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Agendamento_tb_Agendamento", Storage="_tb_Agendamentos", ThisKey="id_Status_Agendamento", OtherKey="id_Status_Agendamento")]
	public EntitySet<tb_Agendamento> tb_Agendamentos
	{
		get
		{
			return this._tb_Agendamentos;
		}
		set
		{
			this._tb_Agendamentos.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.Status_Agendamento = this;
	}
	
	private void detach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.Status_Agendamento = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Agendamento")]
public partial class tb_Agendamento : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_agendamento;
	
	private string _dt_agendamento;
	
	private string _hr_agendamento;
	
	private System.Nullable<int> _id_usuario;
	
	private System.Nullable<int> _id_laboratorio;
	
	private System.Nullable<int> _id_ocorrencia;
	
	private System.Nullable<int> _id_Status_Agendamento;
	
	private System.Nullable<int> _id_Horario;
	
	private EntityRef<Status_Agendamento> _Status_Agendamento;
	
	private EntityRef<tb_Horario> _tb_Horario;
	
	private EntityRef<tb_Laboratorio> _tb_Laboratorio;
	
	private EntityRef<tb_Ocorrencia> _tb_Ocorrencia;
	
	private EntityRef<tb_Usuario> _tb_Usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_agendamentoChanging(int value);
    partial void Onid_agendamentoChanged();
    partial void Ondt_agendamentoChanging(string value);
    partial void Ondt_agendamentoChanged();
    partial void Onhr_agendamentoChanging(string value);
    partial void Onhr_agendamentoChanged();
    partial void Onid_usuarioChanging(System.Nullable<int> value);
    partial void Onid_usuarioChanged();
    partial void Onid_laboratorioChanging(System.Nullable<int> value);
    partial void Onid_laboratorioChanged();
    partial void Onid_ocorrenciaChanging(System.Nullable<int> value);
    partial void Onid_ocorrenciaChanged();
    partial void Onid_Status_AgendamentoChanging(System.Nullable<int> value);
    partial void Onid_Status_AgendamentoChanged();
    partial void Onid_HorarioChanging(System.Nullable<int> value);
    partial void Onid_HorarioChanged();
    #endregion
	
	public tb_Agendamento()
	{
		this._Status_Agendamento = default(EntityRef<Status_Agendamento>);
		this._tb_Horario = default(EntityRef<tb_Horario>);
		this._tb_Laboratorio = default(EntityRef<tb_Laboratorio>);
		this._tb_Ocorrencia = default(EntityRef<tb_Ocorrencia>);
		this._tb_Usuario = default(EntityRef<tb_Usuario>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_agendamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_agendamento
	{
		get
		{
			return this._id_agendamento;
		}
		set
		{
			if ((this._id_agendamento != value))
			{
				this.Onid_agendamentoChanging(value);
				this.SendPropertyChanging();
				this._id_agendamento = value;
				this.SendPropertyChanged("id_agendamento");
				this.Onid_agendamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_agendamento", DbType="VarChar(10)")]
	public string dt_agendamento
	{
		get
		{
			return this._dt_agendamento;
		}
		set
		{
			if ((this._dt_agendamento != value))
			{
				this.Ondt_agendamentoChanging(value);
				this.SendPropertyChanging();
				this._dt_agendamento = value;
				this.SendPropertyChanged("dt_agendamento");
				this.Ondt_agendamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr_agendamento", DbType="VarChar(5)")]
	public string hr_agendamento
	{
		get
		{
			return this._hr_agendamento;
		}
		set
		{
			if ((this._hr_agendamento != value))
			{
				this.Onhr_agendamentoChanging(value);
				this.SendPropertyChanging();
				this._hr_agendamento = value;
				this.SendPropertyChanged("hr_agendamento");
				this.Onhr_agendamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
	public System.Nullable<int> id_usuario
	{
		get
		{
			return this._id_usuario;
		}
		set
		{
			if ((this._id_usuario != value))
			{
				if (this._tb_Usuario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_usuarioChanging(value);
				this.SendPropertyChanging();
				this._id_usuario = value;
				this.SendPropertyChanged("id_usuario");
				this.Onid_usuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_laboratorio", DbType="Int")]
	public System.Nullable<int> id_laboratorio
	{
		get
		{
			return this._id_laboratorio;
		}
		set
		{
			if ((this._id_laboratorio != value))
			{
				if (this._tb_Laboratorio.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_laboratorioChanging(value);
				this.SendPropertyChanging();
				this._id_laboratorio = value;
				this.SendPropertyChanged("id_laboratorio");
				this.Onid_laboratorioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ocorrencia", DbType="Int")]
	public System.Nullable<int> id_ocorrencia
	{
		get
		{
			return this._id_ocorrencia;
		}
		set
		{
			if ((this._id_ocorrencia != value))
			{
				if (this._tb_Ocorrencia.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_ocorrenciaChanging(value);
				this.SendPropertyChanging();
				this._id_ocorrencia = value;
				this.SendPropertyChanged("id_ocorrencia");
				this.Onid_ocorrenciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Status_Agendamento", DbType="Int")]
	public System.Nullable<int> id_Status_Agendamento
	{
		get
		{
			return this._id_Status_Agendamento;
		}
		set
		{
			if ((this._id_Status_Agendamento != value))
			{
				if (this._Status_Agendamento.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_Status_AgendamentoChanging(value);
				this.SendPropertyChanging();
				this._id_Status_Agendamento = value;
				this.SendPropertyChanged("id_Status_Agendamento");
				this.Onid_Status_AgendamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Horario", DbType="Int")]
	public System.Nullable<int> id_Horario
	{
		get
		{
			return this._id_Horario;
		}
		set
		{
			if ((this._id_Horario != value))
			{
				if (this._tb_Horario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_HorarioChanging(value);
				this.SendPropertyChanging();
				this._id_Horario = value;
				this.SendPropertyChanged("id_Horario");
				this.Onid_HorarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Agendamento_tb_Agendamento", Storage="_Status_Agendamento", ThisKey="id_Status_Agendamento", OtherKey="id_Status_Agendamento", IsForeignKey=true)]
	public Status_Agendamento Status_Agendamento
	{
		get
		{
			return this._Status_Agendamento.Entity;
		}
		set
		{
			Status_Agendamento previousValue = this._Status_Agendamento.Entity;
			if (((previousValue != value) 
						|| (this._Status_Agendamento.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Status_Agendamento.Entity = null;
					previousValue.tb_Agendamentos.Remove(this);
				}
				this._Status_Agendamento.Entity = value;
				if ((value != null))
				{
					value.tb_Agendamentos.Add(this);
					this._id_Status_Agendamento = value.id_Status_Agendamento;
				}
				else
				{
					this._id_Status_Agendamento = default(Nullable<int>);
				}
				this.SendPropertyChanged("Status_Agendamento");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Horario_tb_Agendamento", Storage="_tb_Horario", ThisKey="id_Horario", OtherKey="id_Horario", IsForeignKey=true)]
	public tb_Horario tb_Horario
	{
		get
		{
			return this._tb_Horario.Entity;
		}
		set
		{
			tb_Horario previousValue = this._tb_Horario.Entity;
			if (((previousValue != value) 
						|| (this._tb_Horario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Horario.Entity = null;
					previousValue.tb_Agendamentos.Remove(this);
				}
				this._tb_Horario.Entity = value;
				if ((value != null))
				{
					value.tb_Agendamentos.Add(this);
					this._id_Horario = value.id_Horario;
				}
				else
				{
					this._id_Horario = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Horario");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Laboratorio_tb_Agendamento", Storage="_tb_Laboratorio", ThisKey="id_laboratorio", OtherKey="id_Laboratorio", IsForeignKey=true)]
	public tb_Laboratorio tb_Laboratorio
	{
		get
		{
			return this._tb_Laboratorio.Entity;
		}
		set
		{
			tb_Laboratorio previousValue = this._tb_Laboratorio.Entity;
			if (((previousValue != value) 
						|| (this._tb_Laboratorio.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Laboratorio.Entity = null;
					previousValue.tb_Agendamentos.Remove(this);
				}
				this._tb_Laboratorio.Entity = value;
				if ((value != null))
				{
					value.tb_Agendamentos.Add(this);
					this._id_laboratorio = value.id_Laboratorio;
				}
				else
				{
					this._id_laboratorio = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Laboratorio");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Ocorrencia_tb_Agendamento", Storage="_tb_Ocorrencia", ThisKey="id_ocorrencia", OtherKey="id_Ocorrencia", IsForeignKey=true)]
	public tb_Ocorrencia tb_Ocorrencia
	{
		get
		{
			return this._tb_Ocorrencia.Entity;
		}
		set
		{
			tb_Ocorrencia previousValue = this._tb_Ocorrencia.Entity;
			if (((previousValue != value) 
						|| (this._tb_Ocorrencia.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Ocorrencia.Entity = null;
					previousValue.tb_Agendamentos.Remove(this);
				}
				this._tb_Ocorrencia.Entity = value;
				if ((value != null))
				{
					value.tb_Agendamentos.Add(this);
					this._id_ocorrencia = value.id_Ocorrencia;
				}
				else
				{
					this._id_ocorrencia = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Ocorrencia");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Agendamento", Storage="_tb_Usuario", ThisKey="id_usuario", OtherKey="id_Usuario", IsForeignKey=true)]
	public tb_Usuario tb_Usuario
	{
		get
		{
			return this._tb_Usuario.Entity;
		}
		set
		{
			tb_Usuario previousValue = this._tb_Usuario.Entity;
			if (((previousValue != value) 
						|| (this._tb_Usuario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Usuario.Entity = null;
					previousValue.tb_Agendamentos.Remove(this);
				}
				this._tb_Usuario.Entity = value;
				if ((value != null))
				{
					value.tb_Agendamentos.Add(this);
					this._id_usuario = value.id_Usuario;
				}
				else
				{
					this._id_usuario = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Usuario");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ComputadorSoftware")]
public partial class tb_ComputadorSoftware : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_ComputadorSoftware;
	
	private System.Nullable<int> _id_Software;
	
	private System.Nullable<int> _id_Computador;
	
	private EntityRef<tb_Software> _tb_Software;
	
	private EntityRef<tb_Computador> _tb_Computador;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ComputadorSoftwareChanging(int value);
    partial void Onid_ComputadorSoftwareChanged();
    partial void Onid_SoftwareChanging(System.Nullable<int> value);
    partial void Onid_SoftwareChanged();
    partial void Onid_ComputadorChanging(System.Nullable<int> value);
    partial void Onid_ComputadorChanged();
    #endregion
	
	public tb_ComputadorSoftware()
	{
		this._tb_Software = default(EntityRef<tb_Software>);
		this._tb_Computador = default(EntityRef<tb_Computador>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ComputadorSoftware", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_ComputadorSoftware
	{
		get
		{
			return this._id_ComputadorSoftware;
		}
		set
		{
			if ((this._id_ComputadorSoftware != value))
			{
				this.Onid_ComputadorSoftwareChanging(value);
				this.SendPropertyChanging();
				this._id_ComputadorSoftware = value;
				this.SendPropertyChanged("id_ComputadorSoftware");
				this.Onid_ComputadorSoftwareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Software", DbType="Int")]
	public System.Nullable<int> id_Software
	{
		get
		{
			return this._id_Software;
		}
		set
		{
			if ((this._id_Software != value))
			{
				if (this._tb_Software.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_SoftwareChanging(value);
				this.SendPropertyChanging();
				this._id_Software = value;
				this.SendPropertyChanged("id_Software");
				this.Onid_SoftwareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Computador", DbType="Int")]
	public System.Nullable<int> id_Computador
	{
		get
		{
			return this._id_Computador;
		}
		set
		{
			if ((this._id_Computador != value))
			{
				if (this._tb_Computador.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._id_Computador = value;
				this.SendPropertyChanged("id_Computador");
				this.Onid_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Software_tb_ComputadorSoftware", Storage="_tb_Software", ThisKey="id_Software", OtherKey="id_Software", IsForeignKey=true)]
	public tb_Software tb_Software
	{
		get
		{
			return this._tb_Software.Entity;
		}
		set
		{
			tb_Software previousValue = this._tb_Software.Entity;
			if (((previousValue != value) 
						|| (this._tb_Software.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Software.Entity = null;
					previousValue.tb_ComputadorSoftwares.Remove(this);
				}
				this._tb_Software.Entity = value;
				if ((value != null))
				{
					value.tb_ComputadorSoftwares.Add(this);
					this._id_Software = value.id_Software;
				}
				else
				{
					this._id_Software = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Software");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Computador_tb_ComputadorSoftware", Storage="_tb_Computador", ThisKey="id_Computador", OtherKey="id_Computador", IsForeignKey=true)]
	public tb_Computador tb_Computador
	{
		get
		{
			return this._tb_Computador.Entity;
		}
		set
		{
			tb_Computador previousValue = this._tb_Computador.Entity;
			if (((previousValue != value) 
						|| (this._tb_Computador.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Computador.Entity = null;
					previousValue.tb_ComputadorSoftwares.Remove(this);
				}
				this._tb_Computador.Entity = value;
				if ((value != null))
				{
					value.tb_ComputadorSoftwares.Add(this);
					this._id_Computador = value.id_Computador;
				}
				else
				{
					this._id_Computador = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Computador");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Horario")]
public partial class tb_Horario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Horario;
	
	private string _hr_Horario;
	
	private EntitySet<tb_Agendamento> _tb_Agendamentos;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_HorarioChanging(int value);
    partial void Onid_HorarioChanged();
    partial void Onhr_HorarioChanging(string value);
    partial void Onhr_HorarioChanged();
    #endregion
	
	public tb_Horario()
	{
		this._tb_Agendamentos = new EntitySet<tb_Agendamento>(new Action<tb_Agendamento>(this.attach_tb_Agendamentos), new Action<tb_Agendamento>(this.detach_tb_Agendamentos));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Horario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Horario
	{
		get
		{
			return this._id_Horario;
		}
		set
		{
			if ((this._id_Horario != value))
			{
				this.Onid_HorarioChanging(value);
				this.SendPropertyChanging();
				this._id_Horario = value;
				this.SendPropertyChanged("id_Horario");
				this.Onid_HorarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr_Horario", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string hr_Horario
	{
		get
		{
			return this._hr_Horario;
		}
		set
		{
			if ((this._hr_Horario != value))
			{
				this.Onhr_HorarioChanging(value);
				this.SendPropertyChanging();
				this._hr_Horario = value;
				this.SendPropertyChanged("hr_Horario");
				this.Onhr_HorarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Horario_tb_Agendamento", Storage="_tb_Agendamentos", ThisKey="id_Horario", OtherKey="id_Horario")]
	public EntitySet<tb_Agendamento> tb_Agendamentos
	{
		get
		{
			return this._tb_Agendamentos;
		}
		set
		{
			this._tb_Agendamentos.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Horario = this;
	}
	
	private void detach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Horario = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Laboratorio")]
public partial class tb_Laboratorio : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Laboratorio;
	
	private System.Nullable<int> _id_Usuario;
	
	private int _lb_Capacidade;
	
	private string _lb_Arcondicionado;
	
	private string _lb_Projetor;
	
	private string _lb_Numero;
	
	private EntitySet<tb_Agendamento> _tb_Agendamentos;
	
	private EntitySet<tb_Ocorrencia> _tb_Ocorrencias;
	
	private EntitySet<tb_Computador> _tb_Computadors;
	
	private EntityRef<tb_Usuario> _tb_Usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_LaboratorioChanging(int value);
    partial void Onid_LaboratorioChanged();
    partial void Onid_UsuarioChanging(System.Nullable<int> value);
    partial void Onid_UsuarioChanged();
    partial void Onlb_CapacidadeChanging(int value);
    partial void Onlb_CapacidadeChanged();
    partial void Onlb_ArcondicionadoChanging(string value);
    partial void Onlb_ArcondicionadoChanged();
    partial void Onlb_ProjetorChanging(string value);
    partial void Onlb_ProjetorChanged();
    partial void Onlb_NumeroChanging(string value);
    partial void Onlb_NumeroChanged();
    #endregion
	
	public tb_Laboratorio()
	{
		this._tb_Agendamentos = new EntitySet<tb_Agendamento>(new Action<tb_Agendamento>(this.attach_tb_Agendamentos), new Action<tb_Agendamento>(this.detach_tb_Agendamentos));
		this._tb_Ocorrencias = new EntitySet<tb_Ocorrencia>(new Action<tb_Ocorrencia>(this.attach_tb_Ocorrencias), new Action<tb_Ocorrencia>(this.detach_tb_Ocorrencias));
		this._tb_Computadors = new EntitySet<tb_Computador>(new Action<tb_Computador>(this.attach_tb_Computadors), new Action<tb_Computador>(this.detach_tb_Computadors));
		this._tb_Usuario = default(EntityRef<tb_Usuario>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Laboratorio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Laboratorio
	{
		get
		{
			return this._id_Laboratorio;
		}
		set
		{
			if ((this._id_Laboratorio != value))
			{
				this.Onid_LaboratorioChanging(value);
				this.SendPropertyChanging();
				this._id_Laboratorio = value;
				this.SendPropertyChanged("id_Laboratorio");
				this.Onid_LaboratorioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int")]
	public System.Nullable<int> id_Usuario
	{
		get
		{
			return this._id_Usuario;
		}
		set
		{
			if ((this._id_Usuario != value))
			{
				if (this._tb_Usuario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_UsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_Usuario = value;
				this.SendPropertyChanged("id_Usuario");
				this.Onid_UsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lb_Capacidade", DbType="Int NOT NULL")]
	public int lb_Capacidade
	{
		get
		{
			return this._lb_Capacidade;
		}
		set
		{
			if ((this._lb_Capacidade != value))
			{
				this.Onlb_CapacidadeChanging(value);
				this.SendPropertyChanging();
				this._lb_Capacidade = value;
				this.SendPropertyChanged("lb_Capacidade");
				this.Onlb_CapacidadeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lb_Arcondicionado", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string lb_Arcondicionado
	{
		get
		{
			return this._lb_Arcondicionado;
		}
		set
		{
			if ((this._lb_Arcondicionado != value))
			{
				this.Onlb_ArcondicionadoChanging(value);
				this.SendPropertyChanging();
				this._lb_Arcondicionado = value;
				this.SendPropertyChanged("lb_Arcondicionado");
				this.Onlb_ArcondicionadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lb_Projetor", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string lb_Projetor
	{
		get
		{
			return this._lb_Projetor;
		}
		set
		{
			if ((this._lb_Projetor != value))
			{
				this.Onlb_ProjetorChanging(value);
				this.SendPropertyChanging();
				this._lb_Projetor = value;
				this.SendPropertyChanged("lb_Projetor");
				this.Onlb_ProjetorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lb_Numero", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string lb_Numero
	{
		get
		{
			return this._lb_Numero;
		}
		set
		{
			if ((this._lb_Numero != value))
			{
				this.Onlb_NumeroChanging(value);
				this.SendPropertyChanging();
				this._lb_Numero = value;
				this.SendPropertyChanged("lb_Numero");
				this.Onlb_NumeroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Laboratorio_tb_Agendamento", Storage="_tb_Agendamentos", ThisKey="id_Laboratorio", OtherKey="id_laboratorio")]
	public EntitySet<tb_Agendamento> tb_Agendamentos
	{
		get
		{
			return this._tb_Agendamentos;
		}
		set
		{
			this._tb_Agendamentos.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Laboratorio_tb_Ocorrencia", Storage="_tb_Ocorrencias", ThisKey="id_Laboratorio", OtherKey="id_Laboratorio")]
	public EntitySet<tb_Ocorrencia> tb_Ocorrencias
	{
		get
		{
			return this._tb_Ocorrencias;
		}
		set
		{
			this._tb_Ocorrencias.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Laboratorio_tb_Computador", Storage="_tb_Computadors", ThisKey="id_Laboratorio", OtherKey="id_Laboratorio")]
	public EntitySet<tb_Computador> tb_Computadors
	{
		get
		{
			return this._tb_Computadors;
		}
		set
		{
			this._tb_Computadors.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Laboratorio", Storage="_tb_Usuario", ThisKey="id_Usuario", OtherKey="id_Usuario", IsForeignKey=true)]
	public tb_Usuario tb_Usuario
	{
		get
		{
			return this._tb_Usuario.Entity;
		}
		set
		{
			tb_Usuario previousValue = this._tb_Usuario.Entity;
			if (((previousValue != value) 
						|| (this._tb_Usuario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Usuario.Entity = null;
					previousValue.tb_Laboratorios.Remove(this);
				}
				this._tb_Usuario.Entity = value;
				if ((value != null))
				{
					value.tb_Laboratorios.Add(this);
					this._id_Usuario = value.id_Usuario;
				}
				else
				{
					this._id_Usuario = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Usuario");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Laboratorio = this;
	}
	
	private void detach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Laboratorio = null;
	}
	
	private void attach_tb_Ocorrencias(tb_Ocorrencia entity)
	{
		this.SendPropertyChanging();
		entity.tb_Laboratorio = this;
	}
	
	private void detach_tb_Ocorrencias(tb_Ocorrencia entity)
	{
		this.SendPropertyChanging();
		entity.tb_Laboratorio = null;
	}
	
	private void attach_tb_Computadors(tb_Computador entity)
	{
		this.SendPropertyChanging();
		entity.tb_Laboratorio = this;
	}
	
	private void detach_tb_Computadors(tb_Computador entity)
	{
		this.SendPropertyChanging();
		entity.tb_Laboratorio = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Ocorrencia")]
public partial class tb_Ocorrencia : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Ocorrencia;
	
	private System.Nullable<int> _id_Laboratorio;
	
	private int _id_Usuario;
	
	private string _oc_descricao;
	
	private EntitySet<tb_Agendamento> _tb_Agendamentos;
	
	private EntityRef<tb_Laboratorio> _tb_Laboratorio;
	
	private EntityRef<tb_Usuario> _tb_Usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_OcorrenciaChanging(int value);
    partial void Onid_OcorrenciaChanged();
    partial void Onid_LaboratorioChanging(System.Nullable<int> value);
    partial void Onid_LaboratorioChanged();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void Onoc_descricaoChanging(string value);
    partial void Onoc_descricaoChanged();
    #endregion
	
	public tb_Ocorrencia()
	{
		this._tb_Agendamentos = new EntitySet<tb_Agendamento>(new Action<tb_Agendamento>(this.attach_tb_Agendamentos), new Action<tb_Agendamento>(this.detach_tb_Agendamentos));
		this._tb_Laboratorio = default(EntityRef<tb_Laboratorio>);
		this._tb_Usuario = default(EntityRef<tb_Usuario>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ocorrencia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Ocorrencia
	{
		get
		{
			return this._id_Ocorrencia;
		}
		set
		{
			if ((this._id_Ocorrencia != value))
			{
				this.Onid_OcorrenciaChanging(value);
				this.SendPropertyChanging();
				this._id_Ocorrencia = value;
				this.SendPropertyChanged("id_Ocorrencia");
				this.Onid_OcorrenciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Laboratorio", DbType="Int")]
	public System.Nullable<int> id_Laboratorio
	{
		get
		{
			return this._id_Laboratorio;
		}
		set
		{
			if ((this._id_Laboratorio != value))
			{
				if (this._tb_Laboratorio.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_LaboratorioChanging(value);
				this.SendPropertyChanging();
				this._id_Laboratorio = value;
				this.SendPropertyChanged("id_Laboratorio");
				this.Onid_LaboratorioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL")]
	public int id_Usuario
	{
		get
		{
			return this._id_Usuario;
		}
		set
		{
			if ((this._id_Usuario != value))
			{
				if (this._tb_Usuario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_UsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_Usuario = value;
				this.SendPropertyChanged("id_Usuario");
				this.Onid_UsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oc_descricao", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
	public string oc_descricao
	{
		get
		{
			return this._oc_descricao;
		}
		set
		{
			if ((this._oc_descricao != value))
			{
				this.Onoc_descricaoChanging(value);
				this.SendPropertyChanging();
				this._oc_descricao = value;
				this.SendPropertyChanged("oc_descricao");
				this.Onoc_descricaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Ocorrencia_tb_Agendamento", Storage="_tb_Agendamentos", ThisKey="id_Ocorrencia", OtherKey="id_ocorrencia")]
	public EntitySet<tb_Agendamento> tb_Agendamentos
	{
		get
		{
			return this._tb_Agendamentos;
		}
		set
		{
			this._tb_Agendamentos.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Laboratorio_tb_Ocorrencia", Storage="_tb_Laboratorio", ThisKey="id_Laboratorio", OtherKey="id_Laboratorio", IsForeignKey=true)]
	public tb_Laboratorio tb_Laboratorio
	{
		get
		{
			return this._tb_Laboratorio.Entity;
		}
		set
		{
			tb_Laboratorio previousValue = this._tb_Laboratorio.Entity;
			if (((previousValue != value) 
						|| (this._tb_Laboratorio.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Laboratorio.Entity = null;
					previousValue.tb_Ocorrencias.Remove(this);
				}
				this._tb_Laboratorio.Entity = value;
				if ((value != null))
				{
					value.tb_Ocorrencias.Add(this);
					this._id_Laboratorio = value.id_Laboratorio;
				}
				else
				{
					this._id_Laboratorio = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Laboratorio");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Ocorrencia", Storage="_tb_Usuario", ThisKey="id_Usuario", OtherKey="id_Usuario", IsForeignKey=true)]
	public tb_Usuario tb_Usuario
	{
		get
		{
			return this._tb_Usuario.Entity;
		}
		set
		{
			tb_Usuario previousValue = this._tb_Usuario.Entity;
			if (((previousValue != value) 
						|| (this._tb_Usuario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Usuario.Entity = null;
					previousValue.tb_Ocorrencias.Remove(this);
				}
				this._tb_Usuario.Entity = value;
				if ((value != null))
				{
					value.tb_Ocorrencias.Add(this);
					this._id_Usuario = value.id_Usuario;
				}
				else
				{
					this._id_Usuario = default(int);
				}
				this.SendPropertyChanged("tb_Usuario");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Ocorrencia = this;
	}
	
	private void detach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Ocorrencia = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Software")]
public partial class tb_Software : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Software;
	
	private string _sf_nome;
	
	private string _sf_interface;
	
	private string _sf_descricao;
	
	private string _sf_versao;
	
	private EntitySet<tb_ComputadorSoftware> _tb_ComputadorSoftwares;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_SoftwareChanging(int value);
    partial void Onid_SoftwareChanged();
    partial void Onsf_nomeChanging(string value);
    partial void Onsf_nomeChanged();
    partial void Onsf_interfaceChanging(string value);
    partial void Onsf_interfaceChanged();
    partial void Onsf_descricaoChanging(string value);
    partial void Onsf_descricaoChanged();
    partial void Onsf_versaoChanging(string value);
    partial void Onsf_versaoChanged();
    #endregion
	
	public tb_Software()
	{
		this._tb_ComputadorSoftwares = new EntitySet<tb_ComputadorSoftware>(new Action<tb_ComputadorSoftware>(this.attach_tb_ComputadorSoftwares), new Action<tb_ComputadorSoftware>(this.detach_tb_ComputadorSoftwares));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Software", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Software
	{
		get
		{
			return this._id_Software;
		}
		set
		{
			if ((this._id_Software != value))
			{
				this.Onid_SoftwareChanging(value);
				this.SendPropertyChanging();
				this._id_Software = value;
				this.SendPropertyChanged("id_Software");
				this.Onid_SoftwareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sf_nome", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string sf_nome
	{
		get
		{
			return this._sf_nome;
		}
		set
		{
			if ((this._sf_nome != value))
			{
				this.Onsf_nomeChanging(value);
				this.SendPropertyChanging();
				this._sf_nome = value;
				this.SendPropertyChanged("sf_nome");
				this.Onsf_nomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sf_interface", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string sf_interface
	{
		get
		{
			return this._sf_interface;
		}
		set
		{
			if ((this._sf_interface != value))
			{
				this.Onsf_interfaceChanging(value);
				this.SendPropertyChanging();
				this._sf_interface = value;
				this.SendPropertyChanged("sf_interface");
				this.Onsf_interfaceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sf_descricao", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string sf_descricao
	{
		get
		{
			return this._sf_descricao;
		}
		set
		{
			if ((this._sf_descricao != value))
			{
				this.Onsf_descricaoChanging(value);
				this.SendPropertyChanging();
				this._sf_descricao = value;
				this.SendPropertyChanged("sf_descricao");
				this.Onsf_descricaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sf_versao", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string sf_versao
	{
		get
		{
			return this._sf_versao;
		}
		set
		{
			if ((this._sf_versao != value))
			{
				this.Onsf_versaoChanging(value);
				this.SendPropertyChanging();
				this._sf_versao = value;
				this.SendPropertyChanged("sf_versao");
				this.Onsf_versaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Software_tb_ComputadorSoftware", Storage="_tb_ComputadorSoftwares", ThisKey="id_Software", OtherKey="id_Software")]
	public EntitySet<tb_ComputadorSoftware> tb_ComputadorSoftwares
	{
		get
		{
			return this._tb_ComputadorSoftwares;
		}
		set
		{
			this._tb_ComputadorSoftwares.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_ComputadorSoftwares(tb_ComputadorSoftware entity)
	{
		this.SendPropertyChanging();
		entity.tb_Software = this;
	}
	
	private void detach_tb_ComputadorSoftwares(tb_ComputadorSoftware entity)
	{
		this.SendPropertyChanging();
		entity.tb_Software = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Usuario")]
public partial class tb_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Usuario;
	
	private string _u_login;
	
	private string _u_senha;
	
	private string _u_tipo;
	
	private EntitySet<tb_Agendamento> _tb_Agendamentos;
	
	private EntitySet<tb_Laboratorio> _tb_Laboratorios;
	
	private EntitySet<tb_Ocorrencia> _tb_Ocorrencias;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void Onu_loginChanging(string value);
    partial void Onu_loginChanged();
    partial void Onu_senhaChanging(string value);
    partial void Onu_senhaChanged();
    partial void Onu_tipoChanging(string value);
    partial void Onu_tipoChanged();
    #endregion
	
	public tb_Usuario()
	{
		this._tb_Agendamentos = new EntitySet<tb_Agendamento>(new Action<tb_Agendamento>(this.attach_tb_Agendamentos), new Action<tb_Agendamento>(this.detach_tb_Agendamentos));
		this._tb_Laboratorios = new EntitySet<tb_Laboratorio>(new Action<tb_Laboratorio>(this.attach_tb_Laboratorios), new Action<tb_Laboratorio>(this.detach_tb_Laboratorios));
		this._tb_Ocorrencias = new EntitySet<tb_Ocorrencia>(new Action<tb_Ocorrencia>(this.attach_tb_Ocorrencias), new Action<tb_Ocorrencia>(this.detach_tb_Ocorrencias));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Usuario
	{
		get
		{
			return this._id_Usuario;
		}
		set
		{
			if ((this._id_Usuario != value))
			{
				this.Onid_UsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_Usuario = value;
				this.SendPropertyChanged("id_Usuario");
				this.Onid_UsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_login", DbType="VarChar(10)")]
	public string u_login
	{
		get
		{
			return this._u_login;
		}
		set
		{
			if ((this._u_login != value))
			{
				this.Onu_loginChanging(value);
				this.SendPropertyChanging();
				this._u_login = value;
				this.SendPropertyChanged("u_login");
				this.Onu_loginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_senha", DbType="VarChar(8)")]
	public string u_senha
	{
		get
		{
			return this._u_senha;
		}
		set
		{
			if ((this._u_senha != value))
			{
				this.Onu_senhaChanging(value);
				this.SendPropertyChanging();
				this._u_senha = value;
				this.SendPropertyChanged("u_senha");
				this.Onu_senhaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_tipo", DbType="VarChar(20)")]
	public string u_tipo
	{
		get
		{
			return this._u_tipo;
		}
		set
		{
			if ((this._u_tipo != value))
			{
				this.Onu_tipoChanging(value);
				this.SendPropertyChanging();
				this._u_tipo = value;
				this.SendPropertyChanged("u_tipo");
				this.Onu_tipoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Agendamento", Storage="_tb_Agendamentos", ThisKey="id_Usuario", OtherKey="id_usuario")]
	public EntitySet<tb_Agendamento> tb_Agendamentos
	{
		get
		{
			return this._tb_Agendamentos;
		}
		set
		{
			this._tb_Agendamentos.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Laboratorio", Storage="_tb_Laboratorios", ThisKey="id_Usuario", OtherKey="id_Usuario")]
	public EntitySet<tb_Laboratorio> tb_Laboratorios
	{
		get
		{
			return this._tb_Laboratorios;
		}
		set
		{
			this._tb_Laboratorios.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Ocorrencia", Storage="_tb_Ocorrencias", ThisKey="id_Usuario", OtherKey="id_Usuario")]
	public EntitySet<tb_Ocorrencia> tb_Ocorrencias
	{
		get
		{
			return this._tb_Ocorrencias;
		}
		set
		{
			this._tb_Ocorrencias.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Usuario = this;
	}
	
	private void detach_tb_Agendamentos(tb_Agendamento entity)
	{
		this.SendPropertyChanging();
		entity.tb_Usuario = null;
	}
	
	private void attach_tb_Laboratorios(tb_Laboratorio entity)
	{
		this.SendPropertyChanging();
		entity.tb_Usuario = this;
	}
	
	private void detach_tb_Laboratorios(tb_Laboratorio entity)
	{
		this.SendPropertyChanging();
		entity.tb_Usuario = null;
	}
	
	private void attach_tb_Ocorrencias(tb_Ocorrencia entity)
	{
		this.SendPropertyChanging();
		entity.tb_Usuario = this;
	}
	
	private void detach_tb_Ocorrencias(tb_Ocorrencia entity)
	{
		this.SendPropertyChanging();
		entity.tb_Usuario = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Computador")]
public partial class tb_Computador : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Computador;
	
	private System.Nullable<int> _id_Laboratorio;
	
	private string _nm_Computador;
	
	private string _mRam_Computador;
	
	private string _plMae_Computador;
	
	private string _processador_Computador;
	
	private string _st_Computador;
	
	private EntitySet<tb_ComputadorSoftware> _tb_ComputadorSoftwares;
	
	private EntityRef<tb_Laboratorio> _tb_Laboratorio;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ComputadorChanging(int value);
    partial void Onid_ComputadorChanged();
    partial void Onid_LaboratorioChanging(System.Nullable<int> value);
    partial void Onid_LaboratorioChanged();
    partial void Onnm_ComputadorChanging(string value);
    partial void Onnm_ComputadorChanged();
    partial void OnmRam_ComputadorChanging(string value);
    partial void OnmRam_ComputadorChanged();
    partial void OnplMae_ComputadorChanging(string value);
    partial void OnplMae_ComputadorChanged();
    partial void Onprocessador_ComputadorChanging(string value);
    partial void Onprocessador_ComputadorChanged();
    partial void Onst_ComputadorChanging(string value);
    partial void Onst_ComputadorChanged();
    #endregion
	
	public tb_Computador()
	{
		this._tb_ComputadorSoftwares = new EntitySet<tb_ComputadorSoftware>(new Action<tb_ComputadorSoftware>(this.attach_tb_ComputadorSoftwares), new Action<tb_ComputadorSoftware>(this.detach_tb_ComputadorSoftwares));
		this._tb_Laboratorio = default(EntityRef<tb_Laboratorio>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Computador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Computador
	{
		get
		{
			return this._id_Computador;
		}
		set
		{
			if ((this._id_Computador != value))
			{
				this.Onid_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._id_Computador = value;
				this.SendPropertyChanged("id_Computador");
				this.Onid_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Laboratorio", DbType="Int")]
	public System.Nullable<int> id_Laboratorio
	{
		get
		{
			return this._id_Laboratorio;
		}
		set
		{
			if ((this._id_Laboratorio != value))
			{
				if (this._tb_Laboratorio.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_LaboratorioChanging(value);
				this.SendPropertyChanging();
				this._id_Laboratorio = value;
				this.SendPropertyChanged("id_Laboratorio");
				this.Onid_LaboratorioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_Computador", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string nm_Computador
	{
		get
		{
			return this._nm_Computador;
		}
		set
		{
			if ((this._nm_Computador != value))
			{
				this.Onnm_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._nm_Computador = value;
				this.SendPropertyChanged("nm_Computador");
				this.Onnm_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mRam_Computador", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string mRam_Computador
	{
		get
		{
			return this._mRam_Computador;
		}
		set
		{
			if ((this._mRam_Computador != value))
			{
				this.OnmRam_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._mRam_Computador = value;
				this.SendPropertyChanged("mRam_Computador");
				this.OnmRam_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plMae_Computador", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string plMae_Computador
	{
		get
		{
			return this._plMae_Computador;
		}
		set
		{
			if ((this._plMae_Computador != value))
			{
				this.OnplMae_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._plMae_Computador = value;
				this.SendPropertyChanged("plMae_Computador");
				this.OnplMae_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processador_Computador", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string processador_Computador
	{
		get
		{
			return this._processador_Computador;
		}
		set
		{
			if ((this._processador_Computador != value))
			{
				this.Onprocessador_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._processador_Computador = value;
				this.SendPropertyChanged("processador_Computador");
				this.Onprocessador_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_Computador", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string st_Computador
	{
		get
		{
			return this._st_Computador;
		}
		set
		{
			if ((this._st_Computador != value))
			{
				this.Onst_ComputadorChanging(value);
				this.SendPropertyChanging();
				this._st_Computador = value;
				this.SendPropertyChanged("st_Computador");
				this.Onst_ComputadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Computador_tb_ComputadorSoftware", Storage="_tb_ComputadorSoftwares", ThisKey="id_Computador", OtherKey="id_Computador")]
	public EntitySet<tb_ComputadorSoftware> tb_ComputadorSoftwares
	{
		get
		{
			return this._tb_ComputadorSoftwares;
		}
		set
		{
			this._tb_ComputadorSoftwares.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Laboratorio_tb_Computador", Storage="_tb_Laboratorio", ThisKey="id_Laboratorio", OtherKey="id_Laboratorio", IsForeignKey=true)]
	public tb_Laboratorio tb_Laboratorio
	{
		get
		{
			return this._tb_Laboratorio.Entity;
		}
		set
		{
			tb_Laboratorio previousValue = this._tb_Laboratorio.Entity;
			if (((previousValue != value) 
						|| (this._tb_Laboratorio.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Laboratorio.Entity = null;
					previousValue.tb_Computadors.Remove(this);
				}
				this._tb_Laboratorio.Entity = value;
				if ((value != null))
				{
					value.tb_Computadors.Add(this);
					this._id_Laboratorio = value.id_Laboratorio;
				}
				else
				{
					this._id_Laboratorio = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_Laboratorio");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_ComputadorSoftwares(tb_ComputadorSoftware entity)
	{
		this.SendPropertyChanging();
		entity.tb_Computador = this;
	}
	
	private void detach_tb_ComputadorSoftwares(tb_ComputadorSoftware entity)
	{
		this.SendPropertyChanging();
		entity.tb_Computador = null;
	}
}
#pragma warning restore 1591
